steps:
- name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args:
  - build
  - '--no-cache'
  - '-t'
  - '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
  - '.'
  - '-f'
  - Dockerfile
  secretEnv: ['GITHUB_TOKEN']
  id: Build
- name: gcr.io/cloud-builders/docker
  args:
  - push
  - '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
  id: Push
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  args:
  - run
  - services
  - update
  - '$_SERVICE_NAME'
  - '--platform=managed'
  - >-
    --image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
  - >-
    --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
  - '--region=$_DEPLOY_REGION'
  - '--quiet'
  id: Deploy
  entrypoint: gcloud
images:
- '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
logging: CLOUD_LOGGING_ONLY
substitutions:
  _TRIGGER_ID: 8c619834-79be-4ce7-976b-f1b8ceaae5d8
availableSecrets:
  secretManager:
  - versionName: 'projects/${_PROJECT_ID}/secrets/GITHUB_TOKEN/versions/latest'
    env: 'GITHUB_TOKEN'

